name: Build OAAX runtime

on:
  workflow_dispatch:  # Trigger manually or adapt as needed
  push:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install s3cmd
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd

      - name: Configure s3cmd
        run: |
          cat > ~/.s3cfg <<EOF
          [default]
          access_key = ${{ secrets.S3_ACCESS_KEY }}
          secret_key = ${{ secrets.S3_SECRET_KEY }}
          bucket_location = us-east-1
          host_base = ${{ secrets.S3_ENDPOINT_URL }}
          host_bucket = %(bucket)s.${{ secrets.S3_ENDPOINT_URL }}
          use_https = True
          EOF

      - name: Set up environment
        run: bash scripts/setup_env.sh

      - name: Cross-compile runtimes
        run: bash scripts/build-runtimes.sh

      - name: Upload runtimes to S3
        run: |
          bash scripts/upload-to-storage.sh nightly runtime-library/artifacts/*.gz
