name: Build OAAX runtime

on:
  push:
    branches:
      - main
      - 'refs/tags/*'  # Trigger on tags

jobs:
  timeout-minutes: 10  # Set a timeout of 10 minutes for the job
  build-runtimes:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04  # or any other image

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install s3cmd
        run: |
          apt-get update
          apt-get install -y s3cmd

      - name: Configure s3cmd
        run: |
          cat > ~/.s3cfg <<EOF
          [default]
          access_key = ${{ secrets.S3_ACCESS_KEY }}
          secret_key = ${{ secrets.S3_SECRET_KEY }}
          bucket_location = us-east-1
          host_base = ${{ secrets.S3_ENDPOINT_URL }}
          host_bucket = %(bucket)s.${{ secrets.S3_ENDPOINT_URL }}
          use_https = True
          EOF

      - name: Set up environment
        run: bash scripts/setup-env.sh

      - name: Cross-compile runtimes
        run: bash runtime-library/build-runtimes.sh

      - name: Determine version
        id: version
        run: echo "version=${{ github.ref_type == 'tag' && github.ref_name || 'nightly' }}" >> $GITHUB_ENV

      - name: Upload runtimes to S3
        run: |
          bash scripts/upload-to-storage.sh ${{ env.version }} runtime-library/artifacts/*.gz
