name: Delete runtimes and toolchain on PR close

permissions:
  contents: none
  id-token: none

on:
  pull_request:
    types:
      - closed

jobs:
  handle-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Install s3cmd and Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd

      - name: Delete runtimes and toolchain folders from S3
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
        run: |
            version="$GITHUB_HEAD_REF"
            s3cmd_flags="--access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY --host=$S3_ENDPOINT_URL --host-bucket=%(bucket)s.$S3_ENDPOINT_URL --bucket-location=us-east-1 --ssl"
            echo "Deleting artifacts for version: ${version}"
            # shellcheck disable=SC2086
            s3cmd $s3cmd_flags del --recursive "s3://oaax/runtimes/${version}/CPU/" || echo "Warning: No runtime-library found for version ${version}"
            # shellcheck disable=SC2086
            s3cmd $s3cmd_flags del --recursive "s3://oaax/conversion-toolchain/${version}/CPU/" || echo "Warning: No conversion-toolchain found for version ${version}"
